#! /bin/bash

if [ $# -eq 0 ]
then
    echo "Usage: $0 search text in jar"
    exit
fi

text="$@"

find . -iname '*.jar' -printf "unzip -c %p | grep -q '${text}' && echo %p\n" | sh | while read jar; do
    unzip -qq -l $jar | sed 's/.* //' | while read cls; do
        unzip -c $jar $cls | grep -q "${text}" && echo "${jar}:${cls}"
    done
done

