#!/bin/bash

# install pygments
# sudo apt install python-pygments xclip

if type xclip > /dev/null 2>&1; then
    xclip -o | python -m json.tool | pygmentize -l json
elif type pbpaste > /dev/null 2>&1; then
    pbpaste | python -m json.tool | pygmentize -l json
fi