#!/bin/bash

dir="."

if [ $# -gt 0 ]; then
    dir=$1
fi

echo "git pull under directory ${dir}"
find ${dir} -type d -name '.git' -print0 | xargs -P 40 -n 1 -0 -I '{}' sh -c "cd \"{}\"/../ && git pull && pwd && echo '--------------------'" \;
